#!/bin/bash

cmake \
   "-DCMAKE_SYSTEM_NAME=Windows" \
   "-DCMAKE_SYSTEM_PROCESSOR=amd64" \
   "-DCMAKE_C_COMPILER=x86_64-w64-mingw32-clang" \
   "-DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-clang++" \
   "-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres" \
   "-DCMAKE_PREFIX_PATH=/usr/local/lib/x86_64-w64-mingw32/qt5" \
   "$@"
