#!/bin/bash

cmake \
   "-DCMAKE_SYSTEM_NAME=Windows" \
   "-DCMAKE_SYSTEM_PROCESSOR=x86" \
   "-DCMAKE_C_COMPILER=i686-w64-mingw32-clang" \
   "-DCMAKE_CXX_COMPILER=i686-w64-mingw32-clang++" \
   "-DCMAKE_RC_COMPILER=i686-w64-mingw32-windres" \
   "-DCMAKE_PREFIX_PATH=/usr/local/lib/i686-w64-mingw32/qt5" \
   "-DCMAKE_EXE_LINKER_FLAGS=-static" \
   "$@"
